### ISSUE TITLE
question - spark only install on master pi?

### ISSUE THREAD

**Issue by cjbd** [tcharts-boop/raspberry-pi-4-spark-cluster#1]
hello, awesome project, your document is very acurate, i followed your doc precisely, and it works

btw, i'm very new to spark, it seems your tutorial only need to install spark on master pi, this is one of the way to use spark right?
i wonder how slave nodes work without spark software

i also googled a bit and found a different way to install spark: https://medium.com/@jootorres_11979/how-to-install-and-set-up-an-apache-spark-cluster-on-hadoop-18-04-b4d70650ed42, i didn't try it yet

what's the difference? thanks!

**Comment by TedCha** [comment]
Hey! Glad my documentation was helpful in allowing you to recreate the project.  To answer your question, I think the main difference is the Spark Cluster in my project is managed using YARN while the Spark Cluster in the article doesn't seem to setup YARN on the cluster. Spark has it's own cluster management application but I decided to use YARN in my install which allowed for Spark to send jobs to the salve nodes through YARN.

Unfortunately this was a side project for me during my undergraduate study so I don't know much more than that! I found this [article ](https://sujithjay.com/spark/with-yarn )that could most likely provide better information than I can.
